export default {
  LOGIN: 'LOGIN',
  LOGGED_IN: 'LOGGED_IN',
  TRAVELER_PANEL_CLICKED: 'TRAVELER_PANEL_CLICKED',
  TRAVELERS_FETCHED: 'TRAVELERS_FETCHED',
  DESTINATION_TOGGLE: 'DESTINATION_TOGGLE',
  DESTINATION_DELETE: 'DESTINATION_DELETE',
  DESTINATIONS_SAVED: 'DESTINATIONS_SAVED'
}